[tool.ruff]
target-version = "py312"
line-length = 88

[tool.ruff.lint.per-file-ignores]
"app/tests/**" = ["S101", "S106", "S105"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "S"]
ignore = ["B008"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
